services:
  - name: docker
    image: docker:17.12.0-ce-dind
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /run:/run
     - /var:/var:rshared,rbind
     - /lib/modules:/lib/modules
     - /etc/resolv.conf:/etc/resolv.conf
    rootfsPropagation: shared
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
trust:
  org:
    - library
