services:
  - name: docker
    image: docker:17.10.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/run:/var/run:rshared,rbind
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
trust:
  org:
    - library

