repos:
  - path: /pkgs/linuxkit/pkg
    org: linuxkit
  - path: /pkgs/kubernetes/pkg
    org: linuxkit
  - path: /workdir/pkg
    org: desktopless
  - path: /pkgs/desktopless/pkg
    org: desktopless
