image: x-qxl
org: wiin
arches:
  - amd64
config:
  binds:
    - /tmp:/tmp:rshared,rbind
    - /dev:/dev:rshared,rbind
    - /sys:/sys:rshared,rbind
    - /lib/modules:/lib/modules:rshared,rbind
  capabilities:
    - all
