name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7
      id: go
    - uses: actions/checkout@v2
    - run: go get github.com/linuxkit/linuxkit/src/cmd/linuxkit
    - run: go install github.com/linuxkit/linuxkit/src/cmd/linuxkit@latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: "${{secrets.DOCKER_USERNAME}}"
        password: "${{secrets.DOCKER_PASSWORD}}"
    - name: Build the Docker image
      run: make
