name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io/desktopless
    - name: Build the Docker image
      run: make
